### ISSUE TITLE
Add possibility to open linked Object

### ISSUE THREAD

**Issue by kubaplas** [DivanteLtd/pimcore-notifications#5]
Currently there is no way to open linked object beside clicking on popup button. Once popup is gone, possibility to get into object is also gone.

**Comment by kkarkus** [comment]
@kubaplas Please look here, it's available on master.
https://github.com/DivanteLtd/pimcore-notifications/commit/2bd3c75892a57d889d666a170c5b4bec91308b8f#diff-3fef173ca9201463c499d648d365e2e6R88
